### PR TITLE
Added environment as flag for list_containerapp.

### PR DESCRIPTION
**Pull request by haroonf**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Review by StrawnSC — COMMENTED** [review]
The functionality mostly works but there's a logic error when passing the `--env` as an RID. Here's how to repro:
- Create two container app envs with the same name but different RGs (with apps in both)
- run `az containerapp list  --query "[].name" --env {RID of one env}`
- You will see container apps from both envs even though we explicitly pass in the RID (so the user would expect an exact match) 

Unfortunately this will be hard to fix using the preexisting managed_env param because it doesn't say whether it built the RID automatically or the user passed it in. 
The solution here would prob be to use a new param and explicitly handle the case where the user passes in an RID vs when they don't

**Comment by StrawnSC** [comment]
btw for the sake of testing you can get an environment's RID with `az containerapp list ... --query [].id` or `az containerapp show ... --query id`

**Comment by haroonf** [comment]
Fixed logic error, in the case where a g is passed and an RID is passed outside of the g, decided not to error out just return nothing. Let me know if you think an error is better.

**Comment by StrawnSC** [comment]
> Fixed logic error, in the case where a g is passed and an RID is passed outside of the g, decided not to error out just return nothing. Let me know if you think an error is better.

I think this may be a distinct error than the one I was talking about

**Comment by haroonf** [comment]
> > Fixed logic error, in the case where a g is passed and an RID is passed outside of the g, decided not to error out just return nothing. Let me know if you think an error is better.
> 
> I think this may be a distinct error than the one I was talking about

Oh yeah just a thought that came up

**Comment by StrawnSC** [comment]
> > > Fixed logic error, in the case where a g is passed and an RID is passed outside of the g, decided not to error out just return nothing. Let me know if you think an error is better.
> > 
> > 
> > I think this may be a distinct error than the one I was talking about
> 
> Oh yeah just a thought that came up

Right I get what you mean. I think we should raise a resource not found error if the containerapp passed in doesn't exist. It makes sense to me for it to behave the way `--resource-group behaves`. If I just button mash a resource group: I get an error like `(ResourceGroupNotFound) Resource group 'alkjdfakjlsdfk' could not be found.`

This helps users separate the case of "there are no container apps in the this env" from "this env does not exist"

**Pull request merged**
