### PR TITLE
Get repo default branch if --branch not provided (containerapp up --repo)

### PR DESCRIPTION
**Pull request by haroonf**
---

This checklist is used to make sure that common guidelines for a pull request are followed.

### General Guidelines

- [ ] Have you run `azdev style <YOUR_EXT>` locally? (`pip install azdev` required)
- [ ] Have you run `python scripts/ci/test_index.py -q` locally?

For new extensions:

- [ ] My extension description/summary conforms to the [Extension Summary Guidelines](https://github.com/Azure/azure-cli/blob/dev/doc/extensions/extension_summary_guidelines.md).

### About Extension Publish

There is a pipeline to automatically build, upload and publish extension wheels.  
Once your PR is merged into master branch, a new PR will be created to update `src/index.json` automatically.  
The precondition is to put your code inside this repo and upgrade the version in the PR but do not modify `src/index.json`.

### CODE REVIEW

**Comment by panchagnula** [comment]
@StrawnSC  please take a look  & see if this is something that can be incorporated to --repo / github actions add in general. Please ensure we test this thoroughly before we include this.

**Comment by haroonf** [comment]
Will also need to update the param help

**Comment by panchagnula** [comment]
@haroonf & @StrawnSC this change would also need the update to help as well to not say default is "main"

**Comment by StrawnSC** [comment]
Rewrote this on Calvin's main and added the help text change here: https://github.com/calvinsID/azure-cli-extensions/pull/93

I tested E2E with up and github-actions add

**Pull request closed without merging**
